경기 북부:
  - 가평군
  - 양평군
  - 포천시
  - 남양주시
  - 의정부시
  - 동두천시
  - 연천군
  - 파주시

경기 남부:
  - 수원시
  - 용인시
  - 성남시
  - 안양시
  - 안산시
  - 화성시
  - 평택시

강원 영서:
  - 춘천시
  - 원주시
  - 홍천군
  - 횡성군
  - 영월군
  - 평창군
  - 정선군
  - 인제군

강원 영동:
  - 강릉시
  - 속초시
  - 동해시
  - 삼척시
  - 양양군
  - 고성군

충북:
  - 청주시
  - 충주시
  - 제천시
  - 단양군
  - 괴산군
  - 보은군

충남:
  - 천안시
  - 아산시
  - 공주시
  - 부여군
  - 서산시
  - 태안군
  - 보령시

전북:
  - 전주시
  - 군산시
  - 익산시
  - 남원시
  - 무주군
  - 진안군
  - 고창군

전남 동부:
  - 여수시
  - 순천시
  - 광양시
  - 구례군
  - 곡성군

전남 서부:
  - 목포시
  - 나주시
  - 영암군
  - 해남군
  - 완도군

경북 북부:
  - 안동시
  - 영주시
  - 봉화군
  - 울진군
  - 영덕군
  - 문경시

경북 남부:
  - 경주시
  - 포항시
  - 경산시
  - 청도군
  - 영천시

경남 동부:
  - 김해시
  - 양산시
  - 밀양시
  - 창녕군

경남 서부:
  - 창원시
  - 진주시
  - 통영시
  - 거제시
  - 사천시
  - 남해군
  - 하동군

제주:
  - 제주시
  - 서귀포시
