openai:
  temperature: 0.7

wordpress:
  default_category: 1
  default_status: "draft"

content:
  posts_per_day: 3
  min_items: 3
  max_items: 6
  use_ai: true

schedule:
  times:
    - "07:00"
    - "14:00"
    - "20:00"
  timezone: "Asia/Seoul"
